# Generated by Django 3.1.1 on 2020-09-14 01:41

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='Razon razon_social')),
                ('ruc', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Ruc Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='DNI/CEDULA')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('codigo', models.IntegerField(max_length=20, verbose_name='Codigo')),
                ('licencia', models.CharField(max_length=50, verbose_name='Licencia')),
                ('fecha_caducidad_licencia', models.DateField(verbose_name='Fecha de Caducidad')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto de Perfil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
