# Generated by Django 3.1.1 on 2020-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200913_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
